hub: 
 image: selenium/hub:latest
 environment:
    - TZ=Europe/Amsterdam
    - GRID_TIMEOUT=90
 ports:
    - 4444:4444
        
firefox:
 image: selenium/node-firefox:latest
 links:
    - hub:hub
 environment:
    - TZ=Europe/Amsterdam
    - SCREEN_WIDTH=1600
    - SCREEN_HEIGHT=900
    
chrome:
 image: selenium/node-chrome:latest
 links:
    - hub:hub
 environment:
    - TZ=Europe/Amsterdam
    - SCREEN_WIDTH=1600
    - SCREEN_HEIGHT=900
 volumes:
    - c:/xyz:/dev/shm
 privileged: true